/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yourhero;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Random;

/**
 *
 * @author Aung Khant Kyaw
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
        getContentPane().setBackground(new Color(153, 153, 153));
        Clear();
        txtdisplay.setText(Game.game().startGame() + "\n");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtcmd_box = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdisplay = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hero");
        setBackground(new java.awt.Color(204, 204, 204));

        txtcmd_box.setBackground(new java.awt.Color(0, 0, 0));
        txtcmd_box.setForeground(new java.awt.Color(255, 255, 255));
        txtcmd_box.setText("jTextField1");
        txtcmd_box.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                UI.this.keyTyped(evt);
            }
        });

        txtdisplay.setEditable(false);
        txtdisplay.setBackground(new java.awt.Color(0, 0, 0));
        txtdisplay.setColumns(20);
        txtdisplay.setForeground(new java.awt.Color(255, 255, 255));
        txtdisplay.setRows(5);
        jScrollPane1.setViewportView(txtdisplay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(txtcmd_box, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtcmd_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyTyped
        if (evt.getKeyChar() == '\n') {
            String cmd = txtcmd_box.getText().trim();
            String temp = txtdisplay.getText().trim() + "\n>>" + cmd + "\n" ;
            String result = Game.game().Compile(cmd) + "\n";
            if(Game.game().clrscr){ 
                temp = "";
                Game.game().clrscr = false;
                changeColor();
            }
            if(Game.game().gameend){
                txtcmd_box.enable(false);
            }
            txtdisplay.setText(temp + result);
            txtcmd_box.setText("");
            txtcmd_box.requestFocus();
        }
    }//GEN-LAST:event_keyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    
    public void Clear(){
        txtcmd_box.setText("");
        txtdisplay.setText("");
        txtcmd_box.requestFocus();
    }

    public void changeColor(){
        Random r= new Random();
        Color c = new Color(r.nextInt(200), r.nextInt(200), r.nextInt(200));
        txtcmd_box.setBackground(c);
        txtdisplay.setBackground(c);
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcmd_box;
    private javax.swing.JTextArea txtdisplay;
    // End of variables declaration//GEN-END:variables
}
